relativeURLs = true
googleAnalytics = ""
title = "Fabienne Kraemer"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Emre Oral"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Doctoral Researcher"
institution = "GESIS"
logo = "fabienne_workphoto.jpg"
Twitter = "emreoral_"
Email = "fabienne.kraemer@gesis.org"